version: '3.4'
services:

  rabbitmq:
    image: masstransit/rabbitmq:latest
    container_name: rabbitmq
    ports:
     - "5672:5672"
     - "15672:15672"
     - "15692:15692"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    volumes:
      - sqlserverdata:/var/opt/mssql 
    ports:
      - "1401:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - SA_PASSWORD=8jkGh47hnDw89Haq8LN2

  logserver:
    image: datalust/seq:latest
    container_name: logserver
    ports:
      - "5342:80"
    environment:
      - ACCEPT_EULA=Y 

  maildev:
    image: maildev/maildev
    container_name: emailserver
    ports:
      - "1025:25"
      - "1080:80"

volumes:
  sqlserverdata:
  rabbitmqdata:
