start /d "." dotnet run --no-build "./bin/Debug/net6.0/QES.Demo.Worker.dll" --urls="https://localhost:5672"
start /d "." dotnet run --no-build "./bin/Debug/net6.0/QES.Demo.Worker.dll" --urls="https://localhost:5673"
start /d "." dotnet run --no-build "./bin/Debug/net6.0/QES.Demo.Worker.dll" --urls="https://localhost:5674"
start /d "." dotnet run --no-build "./bin/Debug/net6.0/QES.Demo.Worker.dll" --urls="https://localhost:5675"
start /d "." dotnet run --no-build "./bin/Debug/net6.0/QES.Demo.Worker.dll" --urls="https://localhost:5676"
start /d "." dotnet run --no-build "./bin/Debug/net6.0/QES.Demo.Worker.dll" --urls="https://localhost:5677"